spring:
  profiles:
    active: local
    group:
      local: local-server, common, secret

---

spring:
  config:
    activate:
      on-profile: local-server

app:
  server-host: "http://locahost:8080"
  image-configs:
    profile :
      prefix: "${app.server-host}/image/profile"
      dir-path: "${user.dir}/upload/profile"
      default-img: "default.jpg"
    crewProfile :
      prefix: "${app.server-host}/image/crew/profile"
      dir-path: "${user.dir}/upload/crew/profile"
      default-img: "default.jpg"
    crewThumbnail :
      prefix: "${app.server-host}/image/crew/thumbnail"
      dir-path: "${user.dir}/upload/crew/thumbnail"
      default-img: "default.jpg"
    crewGathering :
      prefix: "${app.server-host}/image/crew/gathering"
      dir-path: "${user.dir}/upload/crew/gathering"
      default-img: "default.jpg"
---

spring:
  config:
    activate:
      on-profile: common

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: com.korit.running_back_s2.domain