spring:
  profiles:
    active: local
    group:
      local: local-server, common, secret

---

spring:
  config:
    activate:
      on-profile: local-server
server:
  domain: http://localhost:8080

---

spring:
  config:
    activate:
      on-profile: common

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: com.korit.running_back_s2.domain
  configuration-properties:
    serverHost: "${server.domain}"